services:
  app:
    container_name: spice-visualization-react
    image: spice-visualization-react
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3000